ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview
This project showcases the new and interesting features in Spring Boot 4, including:

* Spring Data JDBC AOT Repositories
* Resilience Features
* Jackson 3
* Null Safety
* RestTestClient
* API Versioning

== Prerequisites
* JDK 25 or greater
* Docker installed and running

== Building
`./mvnw clean install` - to build and run the tests
`./mvnw spring-boot:run` - to start the application

== Installation
Being a showcase project, there is nothing to install.

== Tips and Tricks

=== Data Model
To showcase the new AOT JDBC support, we need a deep data model.

:diagram-type: mermaid

// If we are on GitHub, treat mermaid as a "source" block to trigger their JS renderer
ifdef::env-github[]
:diagram-type: source,mermaid
endif::[]

[{diagram-type}]
----
erDiagram
  ALPHA {
    long id
    string name
  }

  BRAVO {
    long id
    string name
  }

  CHARLIE {
    long id
    string name
  }

  DELTA {
    long id
    string name
  }

  ALPHA 1 to zero or more BRAVO : contains
  BRAVO 1 to zero or more CHARLIE : contains
  BRAVO 1 to zero or more DELTA : contains
----

=== Spring Data AOT
Run `./mvnw clean install` to generate the AOT classes for Spring Data JDBC Repositories. Look at `target/classes/org/kurron/spring/database/AlphaRepository.json` to see what classes implement the various repository methods. Also, see `target/classes/org/kurron/spring/database/AlphaRepositoryImpl__AotRepository.class` for the generated implementation.

== Troubleshooting

== License and Credits
* This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
* See https://github.com/danvega/spring-data-aot/tree/master[Spring Data AOT Coffee Shop Demo] for more examples of Spring Data AOT usage.